---
services:
  stable:
    image: aclemons/slack-lambda:15.0
    build:
      context: .
      dockerfile: stable/Dockerfile
    ports:
      - 9001:8080
    environment:
      - AWS_REGION=eu-central-1
  current:
    image: aclemons/slack-lambda:current
    build:
      context: .
      dockerfile: current/Dockerfile
    ports:
      - 9002:8080
    environment:
      - AWS_REGION=eu-central-1
  current-arm:
    image: aclemons/slack-lambda:current-arm
    build:
      context: .
      dockerfile: current/Dockerfile
    ports:
      - 9003:8080
    environment:
      - AWS_REGION=eu-central-1
