FROM aclemons/slackware:current@sha256:c92e06ea3593d881f81f567cb2dd54baac122138c0e01f8893a1912934100902 as lambda-layers

WORKDIR /tmp
COPY ./extensions/lambda-insights-*.zip .
RUN export TERSE=0 && slackpkg -default_answer=yes -batch=on update && EXIT_CODE=0 && \
    slackpkg -default_answer=yes -batch=on install infozip patchelf || EXIT_CODE=$? && \
    if [ $EXIT_CODE -ne 0 ] && [ $EXIT_CODE -ne 20 ] ; then exit $EXIT_CODE ; fi && \
    rm -rf /var/cache/packages/* && rm -rf /var/lib/slackpkg/* && \
    if [ "$(uname -m)" = "aarch64" ] ; then unzip -q -d /tmp/layer lambda-insights-*arm64*.zip  && patchelf --set-interpreter /lib64/ld-linux-aarch64.so.1 /tmp/layer/extensions/cloudwatch_lambda_agent ; else unzip -q -d /tmp/layer lambda-insights-*amd64*.zip ; fi && \
    rm -- *.zip && removepkg infozip


FROM aclemons/slackware:current@sha256:c92e06ea3593d881f81f567cb2dd54baac122138c0e01f8893a1912934100902

COPY --from=lambda-layers /tmp/layer /opt

RUN export TERSE=0 && slackpkg -default_answer=yes -batch=on update && EXIT_CODE=0 && \
    slackpkg -default_answer=yes -batch=on install brotli ca-certificates cyrus-sasl curl dcron nghttp2 perl || EXIT_CODE=$? && \
    if [ $EXIT_CODE -ne 0 ] && [ $EXIT_CODE -ne 20 ] ; then exit $EXIT_CODE ; fi && \
    rm -rf /var/cache/packages/* && rm -rf /var/lib/slackpkg/* && \
    c_rehash && update-ca-certificates

COPY startup.sh /startup.sh

ENTRYPOINT ["/startup.sh"]
