---
name: Test docker images

on: [pull_request]

env:
  # renovate: datasource=github-releases depName=docker/buildx
  BUILDX_VERSION: "v0.37.1"

jobs:
  ci:
    name: Build and test
    runs-on: ubuntu-26.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false
          persist-credentials: false

      - name: Setup Bats
        uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 # 4.0.0

      - name: Configure binfmt image
        run: |
          BINFMT_IMAGE="$(awk '/^FROM / {print $2}' binfmt/Dockerfile)"
          printf "BINFMT_IMAGE=%s\n" "$BINFMT_IMAGE" >> "$GITHUB_ENV"

      - name: Configure buildkit image
        run: |
          BUILDKIT_IMAGE="$(awk '/^FROM / {print $2}' buildkit/Dockerfile)"
          printf "BUILDKIT_IMAGE=%s\n" "$BUILDKIT_IMAGE" >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
        with:
          image: ${{ env.BINFMT_IMAGE }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
        with:
          version: ${{ env.BUILDX_VERSION }}
          driver-opts: image=${{ env.BUILDKIT_IMAGE }}

      - name: Build 15.0
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          push: false
          platforms: linux/amd64
          cache-from: type=gha,scope=15.0
          context: .
          file: stable/Dockerfile
          provenance: false
          load: true
          tags: |
            aclemons/slack-lambda:15.0

      - name: Build current
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          push: false
          platforms: linux/amd64
          cache-from: type=gha,scope=current
          context: .
          file: current/Dockerfile
          provenance: false
          load: true
          tags: |
            aclemons/slack-lambda:current

      - name: Build current (arm64)
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          push: false
          platforms: linux/arm64/v8
          cache-from: type=gha,scope=current-arm
          context: .
          file: current/Dockerfile
          provenance: false
          load: true
          tags: |
            aclemons/slack-lambda:current-arm

      - name: Start docker compose
        run: |
          docker compose up -d --build --wait --quiet-pull

      - name: Run tests
        run: |
          bats tests
